language: objective-c
matrix:
  include:
    - osx_image: xcode8.1
install:
  - gem install jazzy
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
  # Test that the framework can be installed and built, and passes all unit tests
  - travis_wait pod update
  #- pod lib lint --allow-warnings
  - xcodebuild -workspace 'BluemixAppID.xcworkspace' -scheme 'BluemixAppID' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
 - travis_retry xcodebuild -workspace 'BluemixAppID.xcworkspace' test -scheme 'BluemixAppIDTests' -destination 'platform=iOS Simulator,name=iPhone 6' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO