language: objective-c
matrix:
  include:
    - osx_image: xcode8.1
install:
  - gem install jazzy
before_script:
  - rm -rf ~/Library/Developer/Xcode/DerivedData
script:
  # Test that the framework can be installed and built, and passes all unit tests
  - travis_wait pod update
  - carthage update
  - pod lib lint --allow-warnings
  - xcodebuild -workspace 'AppID.xcworkspace' -scheme 'AppID' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
 # - travis_retry xcodebuild -workspace 'AppID.xcworkspace' test -scheme 'AppID Tests' -destination 'platform=iOS Simulator,name=iPhone 6' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
# When merging or pushing to the master branch, release a new version and publish the API documentation
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && [[ "${TRAVIS_JOB_NUMBER}" = *".2"* ]]; then
      bash scripts/release.sh;
    fi
